//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WishfulCode.EC2RDP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AWSAccessKey {
            get {
                return ((string)(this["AWSAccessKey"]));
            }
            set {
                this["AWSAccessKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AWSSecretKey {
            get {
                return ((string)(this["AWSSecretKey"]));
            }
            set {
                this["AWSSecretKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Administrator")]
        public string DefaultRemoteUsername {
            get {
                return ((string)(this["DefaultRemoteUsername"]));
            }
            set {
                this["DefaultRemoteUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::WishfulCode.EC2RDP.Foundation.SerializableStringDictionary ConnectionSettingsRemoteDrives {
            get {
                return ((global::WishfulCode.EC2RDP.Foundation.SerializableStringDictionary)(this["ConnectionSettingsRemoteDrives"]));
            }
            set {
                this["ConnectionSettingsRemoteDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::WishfulCode.EC2RDP.Foundation.SerializableStringDictionary PrivateKeys {
            get {
                return ((global::WishfulCode.EC2RDP.Foundation.SerializableStringDictionary)(this["PrivateKeys"]));
            }
            set {
                this["PrivateKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::WishfulCode.EC2RDP.Foundation.SerializableStringDictionary ConnectionSettingsUseApiAdminPwd {
            get {
                return ((global::WishfulCode.EC2RDP.Foundation.SerializableStringDictionary)(this["ConnectionSettingsUseApiAdminPwd"]));
            }
            set {
                this["ConnectionSettingsUseApiAdminPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultUseApiAdminPwd {
            get {
                return ((bool)(this["DefaultUseApiAdminPwd"]));
            }
            set {
                this["DefaultUseApiAdminPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartMaximized {
            get {
                return ((bool)(this["StartMaximized"]));
            }
            set {
                this["StartMaximized"] = value;
            }
        }
    }
}
